### ISSUE TITLE
Command 14: ClearIdle

### ISSUE THREAD

**Issue by philplckthun** [rgbkrk/pipboylib#17]
In the protocol documentation by @NimVek it says that command 14 is a command without result, while here it says "ClearIdle". When I wrote my library the TCP connection was closed after 10-20 seconds, which was fixed by sending a periodic command 14, so I suspect this just a keepalive beacon.

I don't know however if that's even what you guys meant with ClearIdle.

Just so it's documented somewhere ;)

**Comment by NimVek** [comment]
In my Testings Command 14 only occures if i touched the display of my android, an hit free space, no button

**Comment by AlexanderDzhoganov** [comment]
The client heartbeat is just 5 zero bytes - type 0, channel 0, size 0.

**Comment by philplckthun** [comment]
So the client can just send the same heartbeat as the server?

**Comment by AlexanderDzhoganov** [comment]
Yes, that's what I'm doing atm and it seems to work (no disconnects so far). See usage of `HEARTBEAT_BUF` [here](https://github.com/AlexanderDzhoganov/pipboyrelay/blob/master/standalone.js#L12)

**Comment by NimVek** [comment]
Yes Heatbeat with the 5 zero bytes, is enough, teh app does it every second, i measured it

**Comment by philplckthun** [comment]
@NimVek @AlexanderDzhoganov An interval of 100ms sounds excessive. So the default interval is 1s? I've sent command 14 every 2s and that was enough as well, so I think the server is pretty tolerant

**Comment by AlexanderDzhoganov** [comment]
I'll change it to 1 second as per @NimVek's measurements.

**Comment by rgbkrk** [comment]
Just clicking around while migrating the relay code over into pipboyrelay and I noticed that command type 14 I'm getting when selecting various SPECIAL or status.

```
[TCP Relay]  ::ffff:192.168.1.67:51782 -> 192.168.1.71:27000
00000000: 7b22 7479 7065 223a 3134 2c22 6172 6773  {"type":14,"args
00000010: 223a 5b5d 2c22 6964 223a 3135 7d         ":[],"id":15}
```

Nevermind that, it's an increasing ID every time the user clicks. I feel like this was discussed elsewhere by @AlexanderDzhoganov and @NimVek too...
