### ISSUE TITLE
Fix map decoding

### ISSUE THREAD

**Issue by nkatsaros** [rgbkrk/pipboylib#23]
For some unknown reason, the fallout client can return the wrong width/height for the map. When I had this problem, even the official iOS Pip-Boy app would render the map incorrectly.

I have a fix for this issue in my project [here](https://github.com/nkatsaros/pipboygo/blob/master/protocol/map.go#L55-L60). I found the fix by looking at [this mod](https://github.com/CyberShadow/csfo4/tree/master/mapfix) by @CyberShadow which fixes the issue in the game itself.

**Comment by rgbkrk** [comment]
Ha, that's great. Thanks for letting us know + linking your fix.
