### ISSUE TITLE
UDP relay is not necessary?

### ISSUE THREAD

**Issue by AlexanderDzhoganov** [rgbkrk/pipboylib#8]
Has anyone figured out what (if any) data gets passed through the UDP socket?

**Comment by NimVek** [comment]
Yes ist figured out ;)
The game answers, which type of it is (PC/PS4) and if its busy or not (another client attached)
So no relay is required but, your host should answer on broadcast request.
So your server ist displayed as discovered host.

**Comment by rgbkrk** [comment]
That's correct! The relay's primary purpose is figuring out the protocol without interfering app <-> game. Writing a client is our next big step and doesn't require the UDP relay. We only need to be able to discover running games on the network, which requires a client socket.
